### ISSUE TITLE
Supported only on Windows(?)

### ISSUE THREAD

**Issue by tolstenko** [brianasu/unity-ray-marching#2]
Awesome work! I just noticed that your shader implementation only works for Windows. I tried to run on OSX, Android, iOS, WebGL and everything goes magenta.

**Comment by brianasu** [comment]
It might be a unity update problem. I actually developed the project on a mac. You should check out the  volumetric-textures branch if you haven't that is going to be merged into master soon.

**Comment by tolstenko** [comment]
I used the "volumetric-textures-depth" branch. Tomorrow I will try volumetric-textures and post a detailed report.

**Comment by tolstenko** [comment]
The working branch for mobile devices and osx is volumetric-textures. Thanks for your time.
