### ISSUE TITLE
Unity 5.4

### ISSUE THREAD

**Issue by cwule** [brianasu/unity-ray-marching#6]
Hi Brian,
Thanks a lot for distributing your code! I have used it for viewing some MRI data and it worked great on Unity 5.3.5. However, after the update to Unity 5.4, there are some issues with the textures, described in more detail here: http://forum.unity3d.com/threads/texture-problem-after-upgrade-from-5-3-to-5-4.422277/

Any chance that you know what could be the reason for this?
Cheers,
cwule

**Comment by Lordinaire** [comment]
Hi cwule,

Try to uncheck the MeshRenderer for the 'Cube'.

**Comment by cwule** [comment]
Hi Lrndr,

That did it, thanks a lot for your help!!!
